### ISSUE TITLE
CentOS/RHEL 8.x packages?

### ISSUE THREAD

**Issue by hetzbh** [poettler-ric/fedora-spec#6]
Hello,

I just wanted to ask - do you plan to change the build to include CentOS 8.x/RHEL 8.x and support ZFS 0.8.x?

Thanks

**Comment by poettler-ric** [comment]
https://download.copr.fedorainfracloud.org/results/poettlerric/zrepl/epel-8-x86_64/01131209-zrepl/zrepl-0.2.1-1.el8.x86_64.rpm built on 2019-12-18 doesn't work?

**Comment by hetzbh** [comment]
Umm, this is zrepl, I was talking about ZFS auto snapshots..

**Comment by poettler-ric** [comment]
Ah, sorry, didn't know that. No, there are no plans to port it to CentOS.
