### ISSUE TITLE
Zrepl 0.3

### ISSUE THREAD

**Issue by igsol** [poettler-ric/fedora-spec#7]
Hi,

Zrepl 0.3 was released several days ago.
Could you please update your packages on [COPR](https://copr.fedorainfracloud.org/coprs/poettlerric/zrepl/packages/)?

Thanks beforehand.

**Comment by awehrfritz** [comment]
+1

**Comment by poettler-ric** [comment]
Build on EPEL 7 fails at the moment. I created a [issue](https://github.com/zrepl/zrepl/issues/367) in the zrepl bug tracker.

**Comment by poettler-ric** [comment]
Update should be updated for zrepl 0.3.0.
This might be the last release for zrepl done on copr since they plan to host the repo on his own page.

Are there any further problems?

**Comment by igsol** [comment]
> Are there any further problems?

Thank you very much for your work. Everything work fine. So far I used package on Fedora 31.
